files:
  - source: /StrongBox/CustomCells/
    translation: /StrongBox/%osx_locale%/CustomCells/%original_file_name%
  - source: /StrongBox/*.strings
    translation: /StrongBox/%osx_locale%/%original_file_name%
  - source: /StrongBox Auto Fill/*.strings
    translation: /StrongBox Auto Fill/%osx_locale%/%original_file_name%
  - source: /MacBox/*.strings
    translation: /MacBox/%osx_locale%/%original_file_name%
  - source: /MacBox-AutoFill/*.strings
    translation: /MacBox-AutoFill/%osx_locale%/%original_file_name%
  - source: /browser-extension/*.json
    translation: /browser-extension/%osx_locale%.json
